builds:
- main: ./cmd/clown/main.go
  ldflags: 
    - -s -w
    - -X github.com/micnncim/clown/cmd/main.Version={{.Version}}
    - -X github.com/micnncim/clown/cmd/main.Revision={{.ShortCommit}}
  goos:
  - linux
  - darwin
  - windows
