builds:
- main: ./cmd/clown/main.go
  ldflags: 
    - -s -w
    - -X github.com/micnncim/clown/pkg/version.Version={{.Tag}}
    - -X github.com/micnncim/clown/pkg/version.Revision={{.ShortCommit}}
  goos:
  - linux
  - darwin
  - windows

# https://goreleaser.com/customization/homebrew/
brews:
- tap:
    owner: micnncim
    name: homebrew-clown
  homepage: https://github.com/micnncim/clown
  description: clown gives you emojis randomly.
  test: |
    system "#{bin}/clown -version"
